server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password:

  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true